# Generated by Django 4.2 on 2026-05-11 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Agua', 'Agua'), ('Fuego', 'Fuego'), ('Tierra', 'Tierra'), ('Electrico', 'Electrico'), ('Planta', 'Planta'), ('Volador', 'Volador'), ('Roca', 'Roca'), ('Hielo', 'Hielo'), ('Dragon', 'Dragon'), ('Sombra', 'Sombra'), ('Normal', 'Normal'), ('Fantasma', 'Fantasma'), ('Lucha', 'Lucha'), ('Psiquico', 'Psiquico'), ('Bicho', 'Bicho'), ('Hada', 'Hada'), ('Acero', 'Acero'), ('Veneno', 'Veneno')], max_length=50)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pokemon_images')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemons', to='pokedex.trainer')),
            ],
        ),
    ]
