# Generated by Django 4.2 on 2026-05-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='heiht',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Z', 'Bicho'), ('R', 'Roca'), ('D', 'Dragon'), ('P', 'Planta'), ('A', 'Agua'), ('W', 'Lucha'), ('Y', 'Psiquico'), ('F', 'Fuego'), ('E', 'Electrico'), ('F', 'Fantasma'), ('S', 'Sombra'), ('X', 'Acero'), ('V', 'Volador'), ('T', 'Tierra'), ('I', 'Hielo'), ('U', 'Veneno'), ('Q', 'Hada'), ('N', 'Normal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
