# Generated by Django 4.2 on 2026-05-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_description_trainer_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso (kg)'),
        ),
    ]
