# Generated by Django 4.2 on 2026-05-06 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer_remove_pokemon_heiht_pokemon_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('N', 'Normal'), ('U', 'Veneno'), ('I', 'Hielo'), ('V', 'Volador'), ('E', 'Electrico'), ('W', 'Lucha'), ('Q', 'Hada'), ('Y', 'Psiquico'), ('Z', 'Bicho'), ('F', 'Fantasma'), ('F', 'Fuego'), ('R', 'Roca'), ('S', 'Sombra'), ('D', 'Dragon'), ('A', 'Agua'), ('T', 'Tierra'), ('X', 'Acero'), ('P', 'Planta')], max_length=50),
        ),
    ]
