# Generated by Django 4.2 on 2026-06-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_height_alter_pokemon_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokedex.trainer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
